"""
Pydantic schemas for request/response models
"""

from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserResponse,
    UserProfileResponse,
    UserListResponse,
    UserStats,
)
from app.schemas.auth import (
    LoginRequest,
    LoginResponse,
    RefreshRequest,
    RefreshResponse,
    TokenData,
)
from app.schemas.repository import (
    RepositoryBase,
    RepositoryCreate,
    RepositoryUpdate,
    RepositoryResponse,
    RepositoryDetailResponse,
    RepositoryListResponse,
    TrendingRepository,
    ReadmeResponse,
    StarRepositoryResponse,
    UnstarRepositoryResponse,
    RepositoryStatsResponse,
)
from app.schemas.topic import (
    TopicBase,
    TopicCreate,
    TopicUpdate,
    TopicResponse,
    TopicListResponse,
    TopicDetailResponse,
    FollowTopicResponse,
    UnfollowTopicResponse,
    UserTopicResponse,
    TopicStatsResponse,
)
from app.schemas.analytics import (
    AnalyticsEventBase,
    AnalyticsEventCreate,
    AnalyticsEventResponse,
    AnalyticsDashboardResponse,
    UserAnalyticsResponse,
    RepositoryAnalyticsResponse,
    SearchAnalyticsResponse,
    EngagementMetrics,
    TrendingMetrics,
)
from app.schemas.common import (
    PaginationParams,
    PaginationMetadata,
    PaginatedResponse,
    SortOrder,
    DateRangeFilter,
    RepositoryFilters,
    SearchFilters,
    ErrorResponse,
    SuccessResponse,
)
from app.schemas.search_history import (
    SearchResultType,
    SearchHistoryBase,
    SearchHistoryCreate,
    SearchHistoryResponse,
    SearchHistoryListResponse,
    SearchAutocompleteResponse,
    PopularSearchesResponse,
)
from app.schemas.notification import (
    NotificationType,
    NotificationBase,
    NotificationCreate,
    NotificationUpdate,
    NotificationResponse,
    NotificationListResponse,
    NotificationStatsResponse,
    MarkAllReadResponse,
    BulkNotificationCreate,
)
from app.schemas.settings import (
    ThemeType,
    SettingsBase,
    SettingsCreate,
    SettingsUpdate,
    SettingsResponse,
    SettingsPreferencesResponse,
)
from app.schemas.suggestion import (
    TopicSuggestionBase,
    TopicSuggestionResponse,
    TopicSuggestionListResponse,
    GenerateSuggestionsResponse,
    DismissSuggestionResponse,
    AcceptSuggestionResponse,
    ExampleRepository,
)
from app.schemas.sync import (
    SyncRequest,
    SyncResponse,
    SyncStatusResponse,
    SyncStatsResponse,
    UserSyncStatusResponse,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserResponse",
    "UserProfileResponse",
    "UserListResponse",
    "UserStats",
    # Auth schemas
    "LoginRequest",
    "LoginResponse",
    "RefreshRequest",
    "RefreshResponse",
    "TokenData",
    # Repository schemas
    "RepositoryBase",
    "RepositoryCreate",
    "RepositoryUpdate",
    "RepositoryResponse",
    "RepositoryDetailResponse",
    "RepositoryListResponse",
    "TrendingRepository",
    "ReadmeResponse",
    "StarRepositoryResponse",
    "UnstarRepositoryResponse",
    "RepositoryStatsResponse",
    # Topic schemas
    "TopicBase",
    "TopicCreate",
    "TopicUpdate",
    "TopicResponse",
    "TopicListResponse",
    "TopicDetailResponse",
    "FollowTopicResponse",
    "UnfollowTopicResponse",
    "UserTopicResponse",
    "TopicStatsResponse",
    # Analytics schemas
    "AnalyticsEventBase",
    "AnalyticsEventCreate",
    "AnalyticsEventResponse",
    "AnalyticsDashboardResponse",
    "UserAnalyticsResponse",
    "RepositoryAnalyticsResponse",
    "SearchAnalyticsResponse",
    "EngagementMetrics",
    "TrendingMetrics",
    # SearchHistory schemas
    "SearchResultType",
    "SearchHistoryBase",
    "SearchHistoryCreate",
    "SearchHistoryResponse",
    "SearchHistoryListResponse",
    "SearchAutocompleteResponse",
    "PopularSearchesResponse",
    # Notification schemas
    "NotificationType",
    "NotificationBase",
    "NotificationCreate",
    "NotificationUpdate",
    "NotificationResponse",
    "NotificationListResponse",
    "NotificationStatsResponse",
    "MarkAllReadResponse",
    "BulkNotificationCreate",
    # Settings schemas
    "ThemeType",
    "SettingsBase",
    "SettingsCreate",
    "SettingsUpdate",
    "SettingsResponse",
    "SettingsPreferencesResponse",
    # Suggestion schemas
    "TopicSuggestionBase",
    "TopicSuggestionResponse",
    "TopicSuggestionListResponse",
    "GenerateSuggestionsResponse",
    "DismissSuggestionResponse",
    "AcceptSuggestionResponse",
    "ExampleRepository",
    # Sync schemas
    "SyncRequest",
    "SyncResponse",
    "SyncStatusResponse",
    "SyncStatsResponse",
    "UserSyncStatusResponse",
    # Common schemas
    "PaginationParams",
    "PaginationMetadata",
    "PaginatedResponse",
    "SortOrder",
    "DateRangeFilter",
    "RepositoryFilters",
    "SearchFilters",
    "ErrorResponse",
    "SuccessResponse",
]
